// Define Action Types
export const ACKNOWLEDGE_INCIDENTS_REQUESTED = "ACKNOWLEDGE_INCIDENTS_REQUESTED";
export const ACKNOWLEDGE_INCIDENTS_COMPLETED = "ACKNOWLEDGE_INCIDENTS_COMPLETED";
export const ACKNOWLEDGE_INCIDENTS_ERROR = "ACKNOWLEDGE_INCIDENTS_ERROR";

export const acknowledgeIncidents = (incidents) => ({
  type: ACKNOWLEDGE_INCIDENTS_REQUESTED,
  incidents
});