// Define Action Types
export const TOGGLE_DISPLAY_ACTION_ALERTS_MODAL_REQUESTED = "TOGGLE_DISPLAY_ACTION_ALERTS_MODAL_REQUESTED";
export const TOGGLE_DISPLAY_ACTION_ALERTS_MODAL_COMPLETED = "TOGGLE_DISPLAY_ACTION_ALERTS_MODAL_COMPLETED";

export const UPDATE_ACTION_ALERTS_MODAL_TYPE_REQUESTED = "UPDATE_ACTION_ALERTS_MODAL_TYPE_REQUESTED";
export const UPDATE_ACTION_ALERTS_MODAL_TYPE_COMPLETED = "UPDATE_ACTION_ALERTS_MODAL_TYPE_COMPLETED";

export const UPDATE_ACTION_ALERTS_MODAL_MESSAGE_REQUESTED = "UPDATE_ACTION_ALERTS_MODAL_MESSAGE_REQUESTED";
export const UPDATE_ACTION_ALERTS_MODAL_MESSAGE_COMPLETED = "UPDATE_ACTION_ALERTS_MODAL_MESSAGE_COMPLETED";

// Define Actions
export const toggleDisplayActionAlertsModal = () => ({
  type: TOGGLE_DISPLAY_ACTION_ALERTS_MODAL_REQUESTED
});

export const updateActionAlertsModalType = (actionAlertsModalType) => ({
  type: UPDATE_ACTION_ALERTS_MODAL_TYPE_REQUESTED,
  actionAlertsModalType
});

export const updateActionAlertsModalMessage = (actionAlertsModalMessage) => ({
  type: UPDATE_ACTION_ALERTS_MODAL_MESSAGE_REQUESTED,
  actionAlertsModalMessage
});