// Define Action Types
export const TOGGLE_INCIDENT_TABLE_SETTINGS_REQUESTED = "TOGGLE_INCIDENT_TABLE_SETTINGS_REQUESTED";
export const TOGGLE_INCIDENT_TABLE_SETTINGS_COMPLETED = "TOGGLE_INCIDENT_TABLE_SETTINGS_COMPLETED";

export const UPDATE_INCIDENT_TABLE_COLUMNS_REQUESTED = "UPDATE_INCIDENT_TABLE_COLUMNS_REQUESTED";
export const UPDATE_INCIDENT_TABLE_COLUMNS_COMPLETED = "UPDATE_INCIDENT_TABLE_COLUMNS_COMPLETED";

export const UPDATE_TEMP_INCIDENT_TABLE_COLUMNS_REQUESTED = "UPDATE_TEMP_INCIDENT_TABLE_COLUMNS_REQUESTED";
export const UPDATE_TEMP_INCIDENT_TABLE_COLUMNS_COMPLETED = "UPDATE_TEMP_INCIDENT_TABLE_COLUMNS_COMPLETED";

// Define Actions
export const toggleIncidentTableSettings = () => ({
  type: TOGGLE_INCIDENT_TABLE_SETTINGS_REQUESTED
});

export const updateIncidentTableColumns = (incidentTableColumns) => ({
  type: UPDATE_INCIDENT_TABLE_COLUMNS_REQUESTED,
  incidentTableColumns
});

export const updateTempIncidentTableColumns = (incidentTableColumns) => ({
  type: UPDATE_TEMP_INCIDENT_TABLE_COLUMNS_REQUESTED,
  incidentTableColumns
});