/* eslint-disable max-len */
// Define Action Types
export const TOGGLE_DISPLAY_INCIDENT_DETAILS_MODAL_REQUESTED = 'TOGGLE_DISPLAY_INCIDENT_DETAILS_MODAL_REQUESTED';
export const TOGGLE_DISPLAY_INCIDENT_DETAILS_MODAL_COMPLETED = 'TOGGLE_DISPLAY_INCIDENT_DETAILS_MODAL_COMPLETED';

export const UPDATE_INCIDENT_DETAILS_MODAL_REQUESTED = 'UPDATE_INCIDENT_DETAILS_MODAL_REQUESTED';
export const UPDATE_INCIDENT_DETAILS_MODAL_COMPLETED = 'UPDATE_INCIDENT_DETAILS_MODAL_COMPLETED';

// Define Actions
export const toggleDisplayIncidentDetailsModal = () => ({
  type: TOGGLE_DISPLAY_INCIDENT_DETAILS_MODAL_REQUESTED,
});

export const updateIncidentDetailsModal = (incident) => ({
  type: UPDATE_INCIDENT_DETAILS_MODAL_REQUESTED,
  incident,
});
